### ISSUE TITLE
Conky 테마 중 하모니카에 적합한 테마를 추가

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonikr-conky#1]
테마를 압축한 파일은 아래 경로에 있습니다.
usr/share/conky-manager/themepacks/default-themes-2.1.cmtp.7z

압축을 해제한 후 테마를 추가하고 동일한 이름 default-themes-2.1.cmtp.7z 으로 압축해서 배포하면 적용됩니다.

**Comment by yeji0407** [comment]
아래 이미지와 같은 캘린더 테마를 추가하여 pr 요청했습니다. 확인 부탁드립니다.
![스크린샷, 2021-04-30 17-36-44](https://user-images.githubusercontent.com/55476302/116671354-ce5c0080-a9db-11eb-8c1a-1bf68e2d9943.png)
